version: "3.9"

networks:
  redisnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16

services:
  redis_service_cluster_default:
    container_name: redis_service_cluster_default
    build: ./
    restart: unless-stopped
    depends_on:
      - redis_cluster_configurer
    networks:
      - redisnet
    ports:
      - 8010:8010

  redis_service_cluster_prod:
    container_name: redis_service_cluster_prod
    build: ./
    restart: unless-stopped
    depends_on:
      - redis_cluster_configurer
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    networks:
      - redisnet
    ports:
      - 8011:8011

  redis_service_cluster_test:
    container_name: redis_service_cluster_test
    build: ./
    restart: unless-stopped
    depends_on:
      - redis_cluster_configurer
    environment:
      - "SPRING_PROFILES_ACTIVE=test"
    networks:
      - redisnet
    ports:
      - 8012:8012

  redis_cluster_configurer:
    container_name: redis_cluster_configurer
    image: redis:latest
    depends_on:
      - redis_1
      - redis_2
      - redis_3
      - redis_1_replica
      - redis_2_replica
      - redis_3_replica
    entrypoint: redis-cli -p 6310 --cluster create 10.0.0.10:6310 10.0.0.20:6320 10.0.0.30:6330 10.0.0.11:6311 10.0.0.21:6321 10.0.0.31:6331 --cluster-yes --cluster-replicas 1
    networks:
      redisnet:
        ipv4_address: 10.0.0.2

  redis_1:
    container_name: redis_1
    build: ./redis_config/
    restart: unless-stopped
    environment:
      X_REDIS_PORT: 6310
    networks:
      redisnet:
        ipv4_address: 10.0.0.10
    ports:
      - 6310:6379

  redis_1_replica:
    container_name: redis_1_replica
    build: ./redis_config/
    restart: unless-stopped
    environment:
      X_REDIS_PORT: 6311
    networks:
      redisnet:
        ipv4_address: 10.0.0.11
    ports:
      - 6311:6379


  redis_2:
    container_name: redis_2
    build: ./redis_config/
    restart: unless-stopped
    environment:
      X_REDIS_PORT: 6320
    networks:
      redisnet:
        ipv4_address: 10.0.0.20
    ports:
      - 6320:6379

  redis_2_replica:
    container_name: redis_2_replica
    build: ./redis_config/
    restart: unless-stopped
    environment:
      X_REDIS_PORT: 6321
    networks:
      redisnet:
        ipv4_address: 10.0.0.21
    ports:
      - 6321:6379

  redis_3:
    container_name: redis_3
    build: ./redis_config/
    restart: unless-stopped
    environment:
      X_REDIS_PORT: 6330
    networks:
      redisnet:
        ipv4_address: 10.0.0.30
    ports:
      - 6330:6379

  redis_3_replica:
    container_name: redis_3_replica
    build: ./redis_config/
    restart: unless-stopped
    environment:
      X_REDIS_PORT: 6331
    networks:
      redisnet:
        ipv4_address: 10.0.0.31
    ports:
      - 6331:6379