app:
  redis-keyspace: default

server:
  port: 8010

spring:
  redis:
    cluster:
      nodes:
        - 10.0.0.10:6310
        - 10.0.0.20:6320
        - 10.0.0.30:6330
      maxRedirects: 2
    connect-timeout: 5000