app:
  redis-keyspace: default

server:
  port: 8010

spring:
  redis:
    cluster:
      nodes:
        - 192.168.0.106:6310
        - 192.168.0.106:6320
        - 192.168.0.106:6330
      maxRedirects: 2
    connect-timeout: 5000